CusmaLinux/svu

- src/main/java/co/edu/itp/svu/config/dbmigrations/V002_AddFunctionaryAuthorityWithUser.java
- src/main/java/co/edu/itp/svu/config/dbmigrations/V003_InitialSetupOffice.java
- src/main/java/co/edu/itp/svu/security/AuthoritiesConstants.java
- src/main/webapp/app/admin/user-management/user-management.service.ts
- src/main/webapp/app/shared/security/authority.ts
In this PR a new authority was added, also was enable the list of authorities in the perfil section of user management
**Migrations**: 
**Refactor**
> Adding additional initial data for offices, users and authorities

- CONTRIBUTING.md
In this **PR** the file `CONTRIBUTING.md` was added to follow a basic workflow for contributing to the **svu** repository.
Fixes #2
> Add the contributing.md file

- .vscode/settings.json
- CHANGELOG.md
- package.json
- pom.xml
> Prepare release 0.1.0

- src/main/java/co/edu/itp/svu/domain/Pqrs.java
- src/main/java/co/edu/itp/svu/repository/OficinaRepository.java
- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/java/co/edu/itp/svu/service/dto/PqrsDTO.java
- src/main/webapp/app/entities/pqrs/pqrs-update.component.ts
- src/main/webapp/app/entities/pqrs/pqrs-update.vue
- src/test/java/co/edu/itp/svu/web/rest/PqrsResourceIT.java
This change request is intended to insert default data in the **fechaCreacion**, **fechaLimite**, estado and **oficinaResponsable** fields.
> Add default fields for pqrs creation

- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/webapp/app/constants.ts
- src/main/webapp/app/entities/pqrs/pqrs-update.component.ts
- src/main/webapp/app/entities/pqrs/pqrs-update.vue
- src/main/webapp/app/entities/pqrs/pqrs.vue
- src/main/webapp/app/shared/model/pqrs.model.ts
- src/main/webapp/i18n/en/pqrs.json
- src/main/webapp/i18n/es/pqrs.json
The view has been modified so that when creating a PQRS only the title, description and upload file fields are shown; the title, description, creation date and response deadline fields are also left for reading.
The status field has also been changed from input type to selection type, to show a list that allows selecting a status.
Fixes #30, #29 
Screenshots
> Modify view to update PQRS

- src/main/java/co/edu/itp/svu/config/SecurityConfiguration.java
- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/java/co/edu/itp/svu/web/rest/PqrsResource.java
- src/main/webapp/app/constants.ts
- src/main/webapp/app/entities/pqrs/pqrs-details.component.ts
- src/main/webapp/app/entities/pqrs/pqrs-details.vue
- src/main/webapp/app/entities/pqrs/pqrs-update.component.ts
- src/main/webapp/app/entities/pqrs/pqrs-update.vue
- src/main/webapp/app/router/entities.ts
- src/main/webapp/i18n/en/global.json
- src/main/webapp/i18n/en/pqrs.json
- src/main/webapp/i18n/es/global.json
- src/main/webapp/i18n/es/pqrs.json
A button is added to the PQRS view for the administrator to close it, also a modal window is added to validate if he/she is sure to close it, this button will only be active for users with ROLE:ADMIN and when the PQRS is not closed.
> Create a security button and modal window to close pqrs

- src/main/webapp/app/entities/pqrs/pqrs-details.vue
The date is highlighted to make it more visible in the PQRS view.
> Highlight deadline

- CHANGELOG.md
- package.json
- pom.xml
> Prepare release 0.2.0

- package-lock.json
- src/main/java/co/edu/itp/svu/service/NotificacionService.java
In this PR was added control of exceptions for mehods in notifications services
> Add control of exceptions for methods in notifications services

- src/main/java/co/edu/itp/svu/config/dbmigrations/V007_AddFrontDeskCsAuthority.java
- src/main/java/co/edu/itp/svu/security/AuthoritiesConstants.java
New migration is created to create new autority and a new user
> Migration to create new athority and user frontDesk

- src/main/java/co/edu/itp/svu/config/dbmigrations/V010_UpdateRespuestaFields.java
- src/main/java/co/edu/itp/svu/config/dbmigrations/V011_AddRelationsToAttachedFile.java
- src/main/java/co/edu/itp/svu/domain/ArchivoAdjunto.java
- src/main/java/co/edu/itp/svu/domain/Pqrs.java
- src/main/java/co/edu/itp/svu/domain/Respuesta.java
- src/main/java/co/edu/itp/svu/service/dto/RespuestaDTO.java
- src/main/java/co/edu/itp/svu/service/dto/api/PublicOfficeDTO.java
- src/main/java/co/edu/itp/svu/service/dto/api/PublicPqrsDTO.java
- src/main/java/co/edu/itp/svu/service/dto/api/PublicResponseDTO.java
- src/main/java/co/edu/itp/svu/service/mapper/RespuestaMapper.java
- src/main/java/co/edu/itp/svu/service/mapper/api/PublicOfficeMapper.java
- src/main/java/co/edu/itp/svu/service/mapper/api/PublicPqrsMapper.java
- src/main/java/co/edu/itp/svu/service/mapper/api/PublicResponseMapper.java
- src/test/java/co/edu/itp/svu/domain/RespuestaAsserts.java
- src/test/java/co/edu/itp/svu/domain/RespuestaTest.java
In this PR was added the necessary DTOs and mappers to handle the public data related to Pqrs, Responses and Attached files
> Create custom DTOs to handle an atomic response in the pqrs model

- src/main/java/co/edu/itp/svu/config/dbmigrations/V012_AddTypeAndFileNumberToPqrs.java
- src/main/java/co/edu/itp/svu/domain/Pqrs.java
- src/main/java/co/edu/itp/svu/domain/enumeration/PqrsType.java
- src/main/java/co/edu/itp/svu/service/dto/PqrsDTO.java
- src/main/java/co/edu/itp/svu/service/dto/api/PublicPqrsDTO.java
In this PR was added the `type` and `fileNumber` fields to pqrs domain
> Add new fields to the PQRS entity

- .github/workflows/cd.yml
- .gitignore
- src/main/docker/app.yml
- src/main/java/co/edu/itp/svu/VentanillaUnicaApp.java
- src/main/java/co/edu/itp/svu/config/ConfigChecker.java
- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/resources/.env.example
- src/main/resources/application-dev.yml
- src/main/resources/config/application-prod.yml
- src/main/resources/config/application.yml
In this PR was added the properties to handle the spring **gmail SMTP** server in dev and prod modes. Also was added a `.env.example` file to make a custom setup of gmal SMTP server in local with a .env file. To protect the important user and password variables, secrets were created in github and the corresponding modifications were made in the `cd.yml` file.
> Configure SMTP server

- src/main/webapp/app/core/components/accordion/accordion.component.ts
- src/main/webapp/app/core/components/accordion/accordion.vue
- src/main/webapp/app/pages/welcome/welcome.component.ts
- src/main/webapp/app/pages/welcome/welcome.vue
- src/main/webapp/app/router/index.ts
- src/main/webapp/app/shared/config/config-bootstrap-vue.ts
- src/main/webapp/app/shared/config/config.ts
- src/main/webapp/content/scss/global.scss
In this PR was added the Welcome page in base to design
https://github.com/user-attachments/assets/5022f95d-e768-4e74-b66a-8f7041ce10fa
> Implement the welcome page

- src/main/java/co/edu/itp/svu/repository/PqrsRepository.java
- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/java/co/edu/itp/svu/web/rest/PqrsResource.java
- src/main/webapp/app/entities/pqrs/pqrs.service.ts
- src/main/webapp/app/pages/consult-requirement/consult-requirement.component.ts
- src/main/webapp/app/pages/consult-requirement/consult-requirement.vue
- src/main/webapp/app/pages/welcome/welcome.vue
- src/main/webapp/app/router/pages.ts
In this PR was added the functionality to consult a requirement (PQRSD) using a **file number**.
https://github.com/user-attachments/assets/cd41c3f9-972b-4738-8a06-b5ec9c6270ba
> Add the page to consult a requirement(PQRSD) by file number

- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/java/co/edu/itp/svu/service/dto/PqrsDTO.java
- src/main/java/co/edu/itp/svu/service/dto/api/PublicPqrsDTO.java
- src/main/webapp/app/entities/pqrs/pqrs-details.component.ts
- src/main/webapp/app/entities/pqrs/pqrs-details.vue
- src/main/webapp/app/entities/pqrs/sidebar.vue
- src/main/webapp/app/entities/respuesta/response-item.component.ts
- src/main/webapp/app/entities/respuesta/response-item.vue
- src/main/webapp/app/entities/respuesta/respuesta-details.vue
- src/main/webapp/app/shared/config/config.ts
In this PR was added the new UI to the login users can review the requirement(PQRSD) details now with responses and a better UI making use of bootstrap-vue components
https://github.com/user-attachments/assets/710f367a-ce3e-4e66-af2e-c9b085057f13
> Frontend: Show answers in pqrs detail to login users

- src/main/java/co/edu/itp/svu/repository/PqrsQueryRepository.java
- src/main/java/co/edu/itp/svu/repository/PqrsQueryRepositoryImpl.java
- src/main/java/co/edu/itp/svu/repository/PqrsRepository.java
- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/java/co/edu/itp/svu/web/rest/PqrsResource.java
- src/main/webapp/app/entities/pqrs/pqrs.component.ts
- src/main/webapp/app/entities/pqrs/pqrs.service.ts
- src/main/webapp/app/entities/pqrs/pqrs.vue
- src/main/webapp/app/shared/config/config-bootstrap-vue.ts
- src/main/webapp/app/shared/config/config.ts
- src/main/webapp/i18n/es/pqrs.json
In this PR was added the search functionality to filter by title and file number the list of requirements(PQRSD)
https://github.com/user-attachments/assets/842d8032-0c54-40c3-be0d-f3bc66ed5bca
> Implement search by file number and title for the list of requirements (PQRDS)

- .github/workflows/build.yml
- pom.xml
In this PR was added the sonar cloud setup in base to the recommend documentation of the official page
> Add the sonar cloud setup with github actions

- pom.xml
- src/main/java/co/edu/itp/svu/service/ExcelReportService.java
- src/main/java/co/edu/itp/svu/service/impl/ExcelReportServiceImpl.java
- src/main/java/co/edu/itp/svu/service/report/PqrsExcelGenerator.java
- src/main/java/co/edu/itp/svu/web/rest/ReportResource.java
- src/main/webapp/app/core/home/home.vue
- src/main/webapp/app/entities/informe-pqrs/informe-pqrs-details.component.ts
- src/main/webapp/app/entities/informe-pqrs/informe-pqrs-details.vue
- src/main/webapp/app/services/reports.service.ts
- src/main/webapp/app/shared/config/config.ts
In this PR was added the implementation to generate .xlsx files from the API and the corresponding request service in the SPA
https://github.com/user-attachments/assets/eb646003-f58c-452d-8e9f-f838361386c0
> Add the option to generate a excel chart in base to a inform document

- src/main/java/co/edu/itp/svu/config/SecurityConfiguration.java
- src/main/resources/config/application-prod.yml
- src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts
- src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue
- src/main/webapp/app/entities/pqrs/pqrs-details.vue
- src/main/webapp/app/entities/pqrs/sidebar.vue
In this PR was added the minor changes related to permissions, UI and review of cloud services
> [Enhance] Add minor variad improvements related to refactorization of notifications feature and performance in GCP VM

- package-lock.json
- package.json
- src/main/java/co/edu/itp/svu/config/dbmigrations/V015_OfficeCreationMigration.java
- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/java/co/edu/itp/svu/service/mapper/OficinaMapper.java
- src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue
- src/main/webapp/app/entities/archivo-adjunto/archivo-adjunto-update.component.ts
- src/main/webapp/app/entities/oficina/oficina-details.vue
- src/main/webapp/app/entities/oficina/oficina-update.component.ts
- src/main/webapp/app/entities/oficina/oficina-update.vue
- src/main/webapp/app/entities/oficina/oficina.service.ts
- src/main/webapp/app/entities/oficina/oficina.vue
- src/main/webapp/app/entities/pqrs/api/public-pqrs-details.component.ts
- src/main/webapp/app/entities/user/user.service.ts
- src/main/webapp/app/main.ts
- src/main/webapp/app/router/account.ts
- src/main/webapp/app/router/entities.ts
- src/main/webapp/app/shared/config/config-bootstrap-vue.ts
- src/main/webapp/app/shared/model/oficina.model.ts
In this PR was improved the office views and added the new offices with his respective users using a migration.
https://github.com/user-attachments/assets/c093cdf5-e283-43c9-ba3b-b9d836aa48df
> [Enhance] Improve office domain workflow

- .github/workflows/cd.yml
- src/main/java/co/edu/itp/svu/config/RestTemplateConfiguration.java
- src/main/java/co/edu/itp/svu/security/recaptcha/RecaptchaAspect.java
- src/main/java/co/edu/itp/svu/security/recaptcha/RecaptchaValidationException.java
- src/main/java/co/edu/itp/svu/security/recaptcha/ValidateRecaptcha.java
- src/main/java/co/edu/itp/svu/service/RecaptchaService.java
- src/main/java/co/edu/itp/svu/web/rest/AuthenticateController.java
- src/main/java/co/edu/itp/svu/web/rest/PqrsResource.java
- src/main/java/co/edu/itp/svu/web/rest/vm/RecaptchaResponseVM.java
- src/main/resources/.env.example
- src/main/resources/config/application-dev.yml
- src/main/resources/config/application-prod.yml
- src/main/webapp/app/account/login-form/login-form.component.ts
- src/main/webapp/app/entities/pqrs/api/public-pqrs-create.component.ts
- src/main/webapp/app/entities/pqrs/api/public-pqrs-details.component.ts
- src/main/webapp/app/entities/pqrs/pqrs.service.ts
- src/main/webapp/app/pages/consult-requirement/consult-requirement.component.ts
- src/main/webapp/app/shared/composables/use-recaptcha.ts
- src/main/webapp/index.html
In this PR was added the recaptcha verification to avoid the request of bots in the public endpoints
https://drive.google.com/file/d/1kiVObSOLOmXOJQaI-Zs20cxwey-V913C/view?usp=sharing
> Add the service of reCAPTCHA v3 to protect public forms

- .vscode/settings.json
- package-lock.json
- src/main/java/co/edu/itp/svu/domain/Respuesta.java
- src/main/java/co/edu/itp/svu/repository/ArchivoAdjuntoRepository.java
- src/main/java/co/edu/itp/svu/repository/AttachedFileQueryRepository.java
- src/main/java/co/edu/itp/svu/repository/AttachedFileQueryRepositoryImpl.java
- src/main/java/co/edu/itp/svu/service/ArchivoAdjuntoService.java
- src/main/java/co/edu/itp/svu/web/rest/ArchivoAdjuntoResource.java
- src/main/webapp/app/entities/archivo-adjunto/archivo-adjunto-details.vue
- src/main/webapp/app/entities/archivo-adjunto/archivo-adjunto.component.ts
- src/main/webapp/app/entities/archivo-adjunto/archivo-adjunto.service.ts
- src/main/webapp/app/entities/archivo-adjunto/archivo-adjunto.vue
In this PR was added the search filter to attachments panel
https://github.com/user-attachments/assets/d67321b1-56d4-4192-a7ac-6be6ba3a13e0
> Add search filter to attachments panel

- src/main/java/co/edu/itp/svu/service/UserService.java
- src/main/java/co/edu/itp/svu/service/dto/AdminUserDTO.java
- src/main/webapp/app/admin/user-management/user-management-edit.component.ts
- src/main/webapp/app/admin/user-management/user-management-edit.vue
- src/main/webapp/i18n/en/global.json
- src/main/webapp/i18n/es/global.json
In this PR was added the option to create or update a user with password. Also was added translations to handle the different errors in Spanish lang
https://github.com/user-attachments/assets/8213d760-d192-49b0-907a-5fcd6fc0c816
> Add password change in management users

- src/main/java/co/edu/itp/svu/service/RespuestaService.java
- src/main/webapp/app/entities/oficina/oficina-update.component.ts
- src/main/webapp/app/entities/pqrs/api/public-pqrs-details.component.ts
- src/main/webapp/app/entities/pqrs/api/public-pqrs-details.vue
- src/main/webapp/app/entities/respuesta/respuesta-update.component.ts
- src/main/webapp/app/entities/respuesta/respuesta-update.vue
- src/main/webapp/app/entities/respuesta/respuesta.vue
- src/main/webapp/app/entities/user/user.service.ts
A greater number of users were added to the multiselect when creating an office. Also was improved the UI of response-update page and was added a better look and feel for the reply form in the public pqrs details and finally was added the functionality of edit the attached files in a response. 
https://github.com/user-attachments/assets/78422662-192b-49fd-addc-2ee752431cfe
> Increase the number of users in offices and improve the UI of the response page.

- pom.xml
- src/main/java/co/edu/itp/svu/config/GeminiClientConfig.java
- src/main/java/co/edu/itp/svu/service/FileExtractorService.java
- src/main/java/co/edu/itp/svu/service/GeminiService.java
- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/java/co/edu/itp/svu/web/rest/PqrsResource.java
- src/main/resources/.env.example
- src/main/resources/config/application-dev.yml
- src/main/resources/config/application-prod.yml
In this PR was added the functionality to suggest an office by means of Gemini models
https://github.com/user-attachments/assets/1ac0be7b-d6c5-45de-b4e8-9a2081a7420c
> Suggest the office using Gemini models

- src/main/java/co/edu/itp/svu/service/PqrsService.java
- src/main/java/co/edu/itp/svu/web/rest/PqrsResource.java
- src/main/webapp/app/entities/pqrs/pqrs-details.component.ts
- src/main/webapp/app/entities/pqrs/pqrs-details.vue
- src/main/webapp/app/entities/pqrs/pqrs.service.ts
- src/main/webapp/app/entities/pqrs/sidebar.ts
- src/main/webapp/app/entities/pqrs/sidebar.vue
- src/main/webapp/app/shared/composables/use-permissions.ts
- src/main/webapp/app/shared/config/config.ts
In this PR was added a new button to the sidebar to suggest and assign an office using Gemini
https://github.com/user-attachments/assets/ae39a50f-4c24-46de-83eb-6970a76da598
> Add a button that allows frontdesk user to ask Gemini models to suggest an office
